-- Simple RBAC Setup for Fraud Detection Pipeline
-- Creates two roles: fraud_analyst (read-only) and fraud_admin (full access)

USE DATABASE FRAUD_DETECTION_DB;

-- Create roles
CREATE ROLE IF NOT EXISTS fraud_analyst;
CREATE ROLE IF NOT EXISTS fraud_admin;

-- Fraud Analyst: Read-only access to marts
GRANT USAGE ON DATABASE FRAUD_DETECTION_DB TO ROLE fraud_analyst;
GRANT USAGE ON SCHEMA FRAUD_DETECTION_DB.MARTS TO ROLE fraud_analyst;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE fraud_analyst;
GRANT SELECT ON ALL TABLES IN SCHEMA FRAUD_DETECTION_DB.MARTS TO ROLE fraud_analyst;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FRAUD_DETECTION_DB.MARTS TO ROLE fraud_analyst;

-- Fraud Admin: Broad privileges for pipeline development and experimentation
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE fraud_admin;
GRANT ALL PRIVILEGES ON DATABASE FRAUD_DETECTION_DB TO ROLE fraud_admin;
GRANT ALL PRIVILEGES ON SCHEMA FRAUD_DETECTION_DB.RAW TO ROLE fraud_admin;
GRANT ALL PRIVILEGES ON SCHEMA FRAUD_DETECTION_DB.MARTS TO ROLE fraud_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FRAUD_DETECTION_DB.RAW TO ROLE fraud_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FRAUD_DETECTION_DB.MARTS TO ROLE fraud_admin;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FRAUD_DETECTION_DB.RAW TO ROLE fraud_admin;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FRAUD_DETECTION_DB.MARTS TO ROLE fraud_admin;

-- Note: To use these roles, assign them to users:
-- GRANT ROLE fraud_analyst TO USER <username>;
-- GRANT ROLE fraud_admin TO USER <username>;

